site_name: SD Worx Innovation Lab Handbook
site_description: A handbook for Innovation Lab coaches
pages:
    - Home: index.md
    - Phases:
        - Inspire: phases/inspire.md
        - Explore: phases/explore.md
        - Incubate: phases/incubate.md
        - Accelerate: phases/accelerate.md
        - Grow: phases/grow.md
    - Tools:
        - Playbook: tools/playbook.md
        - Software: tools/software.md
        - Templates: tools/templates.md
    - Workshops: workshops.md
    - FAQ: faq.md
theme: readthedocs
repo_url: https://github.com/djbart/innovationlab-handbook